import Link from "next/link";
import { getProducts } from "../../data/products";
import { Plus } from "lucide-react";
import Dropdown from "../../comp/Dropdown";
import Image from "next/image";
import TableSearchForm from "../../comp/TableSearchForm";

export const metadata = {
  title: "SPS | products Set",
  description: "Generated by create next app",
};

export default async function ProductTable({ searchParams }) {
  const { key, value } = await searchParams;
  console.log(key, value);

  const products = await getProducts(key, value, 20);

  return (
    // Use h-screen and overflow-hidden on the main container to prevent page scrolling
    <div className="md:p-8 bg-gray-50 h-screen overflow-hidden flex flex-col">
      <div className="bg-white shadow-lg rounded-lg p-4 md:p-6 flex flex-col h-full">
        {/* Header Section (Fixed Position within the view) */}
        <div className="flex flex-col md:flex-row justify-between items-center mb-4 pb-4 border-b border-gray-200 flex-shrink-0">
          <div className="w-full md:w-auto flex justify-between items-center mb-4 md:mb-0">
            <span className="text-2xl font-semibold text-gray-800">
              Products list
            </span>
            <Link
              href="/Dashboard/productsSet/prod_add"
              className="flex items-center gap-2 bg-indigo-600 hover:bg-indigo-700 text-white font-semibold py-2 px-4 rounded-lg shadow transition duration-150 ease-in-out"
            >
              <Plus size={18} />
              Add Product
            </Link>
          </div>
          <TableSearchForm />
        </div>

        {/* Table Container (This div will handle the vertical scrolling) */}
        {/* We use flex-grow to make it take up remaining vertical space and overflow-y-auto to enable vertical scrolling */}
        <div className="grow overflow-y-auto">
          {/* Use table-fixed class to ensure columns respect specified widths */}
          <table className="min-w-full divide-y divide-gray-200 table-fixed">
            <thead className="bg-gray-100 sticky top-0">
              {/* Sticky header for better UX */}
              <tr>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider w-16">
                  Img
                </th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider w-1/2">
                  Name
                </th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider w-24">
                  Cost
                </th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider w-32">
                  Category
                </th>
                <th className="px-6 py-3 text-center text-xs font-medium text-gray-500 uppercase tracking-wider w-24">
                  Actions
                </th>
              </tr>
            </thead>
            <tbody className="bg-white divide-y divide-gray-200">
              {products && products.length > 0 ? (
                products.map((row) => (
                  <tr
                    key={row.productId}
                    className="even:bg-gray-50 hover:bg-gray-100 transition duration-150"
                  >
                    <td className="px-6 py-4 whitespace-nowrap">
                      <Link href={"/products/" + row.productId}>
                        <div className="relative h-10 w-10">
                          <Image
                            src={row.p_imgs[0].url}
                            fill
                            sizes="10vw"
                            alt="pro Img"
                            className="rounded-full object-cover"
                          />
                        </div>
                      </Link>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900 truncate">
                      {row.p_name}
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                      ${row.p_cost}
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                      {row.p_cat}
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <div className="flex justify-center">
                        <Dropdown id={row.productId} />
                      </div>
                    </td>
                  </tr>
                ))
              ) : (
                <tr>
                  <td
                    colSpan="5"
                    className="px-6 py-4 text-center text-gray-500"
                  >
                    0 results
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
