import Link from "next/link";
import SearchForm from "../../comp/SearchForm";
import { getProducts } from "../../data/products";
import { Plus } from "lucide-react";
import Dropdown from "../../comp/Dropdown";
import Image from "next/image";
export const metadata = {
  title: "SPS | products Set",
  description: "Generated by create next app",
};
export default async function ProductTable({ searchParams }) {
  const { search_word } = await searchParams;
  const products = await getProducts(search_word, 20);

  return (
    <div>
      <div className="bg-white flex justify-between items-center mb-2 p-2 border-b shadow flex-wrap">
        <div className="w-full flex justify-between items-center mb-2">
          <span> Products list </span>
          <Link
            href="/Dashboard/productsSet/prod_add"
            className="add_product_link flex justify-center items-center gap-1"
          >
            <Plus size={20} />
            Add Product
          </Link>
        </div>
        <SearchForm />
      </div>
      <table>
        <thead>
          <tr className="table_header">
            <td>Img</td>
            <td className="w-full">Name</td>
            <td>Cost</td>
            <td>Category</td>
            <td>Actions</td>
          </tr>
        </thead>
        <tbody>
          {products && products.length > 0 ? (
            products.map((row) => (
              <tr key={row.id} className="">
                <td className=" m-0 p-0">
                  <Link
                    href={"/products/" + row.id}
                    className="flex items-center justify-center rounded-full relative m-0 w-full h-6"
                  >
                    <Image
                      src={row.p_imgs[0].url}
                      fill
                      sizes="10"
                      alt="pro Img"
                      className="rounded-full"
                    />
                  </Link>
                </td>
                <td>{`${row.p_name.slice(0, 20)}`}</td>
                <td className="td_cost">${row.p_cost}</td>
                <td>{row.p_cat}</td>
                <td className="flex justify-center">
                  <Dropdown id={row.id} />
                </td>
              </tr>
            ))
          ) : (
            <tr>
              <td colSpan="5" style={{ textAlign: "center" }}>
                0 results
              </td>
            </tr>
          )}
        </tbody>
      </table>
    </div>
  );
}
