import React from "react";
import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { Avatar, AvatarFallback, AvatarImage } from "@radix-ui/react-avatar";
import { Search, Settings } from "lucide-react";
import { Toaster } from "@/components/ui/sonner";

const roboto = Nunito({
  weight: "500",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "local-host",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.className} antialiased`}>
        <Toaster position="top-center" expand />
        <Navbar />
        {children}
      </body>
    </html>
  );
}
function Navbar() {
  return (
    <nav className=" backdrop-blur-3xl sticky top-0 right-0  z-20  opacity-95">
      <div className="flex justify-between items-center">
        <Link href={"/"} className="logo">
          Elneelen shop
        </Link>{" "}
        <Link className="p-1 flex gap-1 items-center" href="/products">
          <Search size={18} />
        </Link>
      </div>

      <div className="flex m-2 p-0.5 rounded-full border border-gray-400 justify-around items-center">
        <Link className="flex items-center" href="/Dashboard/productsSet">
          <Settings size={18} />
        </Link>
        <Avatar>
          <AvatarImage
            width={30}
            className="rounded-full"
            src="https://github.com/evilrabbit.png"
          />
          <AvatarFallback className="m-1">CN</AvatarFallback>
        </Avatar>
      </div>
    </nav>
  );
}
