import type { Metadata } from "next";
import { Linden_Hill, Nunito } from "next/font/google";
import "./globals.css";
import Head from "next/head";
import Link from "next/link";

const roboto = Nunito({
  weight: "500",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "local-host",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.className}  antialiased`}>
        <nav>
          <div className="logo"> Elneelen shop</div>
          <div>
            <Link href="/products">Home</Link>
            <Link href="/products/productsSet">Settings</Link>
            <Link href="/products">Login</Link>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
