import ProductsCarousel from "../components/ProductsCarousel";
import Hero from "../components/Hero";
import Categories from "../components/Categories";
import ProductGrid from "../components/ProductGrid";
import { getProducts } from "@/services/productsServices";
export const revalidate = 15; // revalidate at most every hour
export const metadata = {
  title: "SPS | products Home",
  description: "Generated by create next app",
};

export default async function Home() {
  const products = await getProducts();
  return (
    <>
      <Hero />
      <h2 className="text-3xl font-extrabold text-gray-800 my-8 text-center">
        Featured PC Components
      </h2>
      <ProductGrid products={products.slice(0, 4)} />
      <ProductsCarousel products={products} />
      <Categories />
      {/* <div className="text-2xl ps-2 text-center py-4">Most Viewed Products</div> */}
      {/* <ProductsList products={products.slice(0, 10)} />; */}
    </>
  );
}
