// "use client";
import { collection, getDocs, limit, query } from "firebase/firestore";
import Link from "next/link";
import { db } from "./db/firebase";

export const metadata = {
  title: "SPS | products",
  description: "Generated by create next app",
};

export default async function Home() {
  const productsRef = collection(db, "products");
  const limitQ = query(productsRef, limit(500));
  const querySnapshot = await getDocs(limitQ);
  const products = querySnapshot.docs.map((doc) => ({
    ...doc.data(),
    id: doc.id,
  }));

  return (
    <>
      <div className="mt-1"></div>
      <div className="list">
        {products && products?.length > 0 ? (
          products.map((row) => (
            <div className="product_card" key={row.id}>
              <Link href={`products/${row.id}`}>
                <div className="img_container">
                  <img src={row.p_img} alt="Product Image" />
                </div>
              </Link>
              <div className="name">{row.p_name}</div>
              <div className="wrapper">
                <span className="cost">{row.p_cost}</span>
                <span className="category"> | {row.p_cat}</span>
              </div>
            </div>
          ))
        ) : (
          <div className="no_product">No products available</div>
        )}
      </div>
    </>
  );
}
