import { getProducts } from "./data/products";
import ProductsList from "./comp/productsList";
import Signin from "./comp/Signin";
import Signout from "./comp/Signout";
import { auth } from "@/auth";
import { log } from "console";
export const revalidate = 15; // revalidate at most every hour
export const metadata = {
  title: "SPS | products Home",
  description: "Generated by create next app",
};

export default async function Home() {
  function wait(ms) {
    return new Promise((resolve) => setTimeout(resolve, ms));
  }
  // await wait(3000);
  const products = await getProducts("all", 500);
  const sess = await auth();
  // log(sess?.);
  // console.log("revalidate homepage ----"); // image url for MON

  return (
    <>
      <Signin />
      <Signout />
      <ProductsList products={products} />;
    </>
  );
}
