import ProductsCarousel from "../components/ProductsCarousel";
import Hero from "../components/Hero";
import Categories from "../components/Categories";
import ProductGrid from "../components/ProductGrid";
import { getProducts } from "@/services/productsServices";
export const revalidate = 15; // revalidate at most every hour
export const metadata = {
  title: "SPS | products Home",
  description: "Generated by create next app",
};

export default async function Home() {
  const products = await getProducts();
  return (
    <>
      <Hero />
      
      <main className="container mx-auto px-4 md:px-6 py-12 space-y-20">
        <section id="shop" className="scroll-mt-24 space-y-10">
          <div className="flex flex-col items-center text-center space-y-4">
            <h2 className="text-3xl md:text-5xl font-black text-slate-900 tracking-tight">
              Featured Components
            </h2>
            <p className="text-slate-500 max-w-2xl mx-auto text-lg">
              Upgrade your rig with our top-rated selections for performance and aesthetics.
            </p>
          </div>
          <ProductGrid products={products.slice(0, 4)} />
        </section>

        <section className="space-y-10">
           <ProductsCarousel products={products} />
        </section>

        <Categories />
      </main>
    </>
  );
}
