import { getProducts } from "./data/products";
import ProductsList from "./comp/productsList";
import Signin from "./comp/Signin";
import Signout from "./comp/Signout";
export const revalidate = 15; // revalidate at most every hour
export const metadata = {
  title: "SPS | products Home",
  description: "Generated by create next app",
};

export default async function Home() {
  const products = await getProducts("all", 500);
  // console.log("revalidate homepage ----"); // image url for MON
  return (
    <>
      <ProductsList products={products} />;
    </>
  );
}
