import Link from "next/link";
import Dlt_btn from "../../comp/dlt_btn";
import SearchForm from "../../comp/SearchForm";
import { getProducts } from "../../data/products";

export const metadata = {
  title: "SPS | products Set",
  description: "Generated by create next app",
};
export default async function ProductTable({ searchParams }) {
  const { search_word } = await searchParams;
  const products = await getProducts(search_word, 20);

  return (
    <table>
      <thead>
        <tr>
          <td colSpan="2" className="font-bold text-sm">
            Products
          </td>
          <td colSpan="2" className="text-right">
            <Link
              href="/products/productsSet/prod_add"
              className="add_product_link w-full"
            >
              Add Product
            </Link>
          </td>
        </tr>
        <tr>
          <td colSpan={4}>
            <SearchForm />
          </td>
        </tr>
        <tr className="table_header">
          <td className="w-full">Name</td>
          <td>Cost</td>
          <td>Category</td>
          <td>Actions</td>
        </tr>
      </thead>
      <tbody>
        {products && products.length > 0 ? (
          products.map((row) => (
            <tr key={row.id}>
              <td>{row.p_name}</td>
              <td>{row.p_cost}</td>
              <td>{row.p_cat}</td>
              <td className="flex justify-center">
                <Link className="edit_btn" href={`productsSet/${row.id}`}>
                  Edit
                </Link>
                <Dlt_btn id={row.id} />
              </td>
            </tr>
          ))
        ) : (
          <tr>
            <td colSpan="5" style={{ textAlign: "center" }}>
              0 results
            </td>
          </tr>
        )}
      </tbody>
    </table>
  );
}
