export async function generateStaticParams() {
  // console.log(await getProductsIds());

  return await getProductsIds();
}

export const revalidate = 15;
export const metadata = {
  title: `SPS | product detail`,
  description: "Generated by create next app",
};
import {
  getDoc,
  doc,
  getDocs,
  query,
  collection,
  where,
  limit,
} from "firebase/firestore";
import { db } from "../../db/firebase";
import ProductImgCarousel from "@/app/comp/carousel";
import { getProductsIds } from "../../actions/product_ids";
import CarouselDial from "../../comp/CarouselDial";
import WishlistBtn from "../../comp/WishlistBtn";
import ProductsList from "./../../comp/productsList";

export default async function ProductsDetails({ params }) {
  const { productId } = await params;
  const docRef = doc(db, "productsTest", productId);
  const docsnapshot = await getDoc(docRef);
  const product = docsnapshot.exists() ? docsnapshot.data() : {};
  const productsRef = collection(db, "productsTest");
  // console.log(product);

  const q = query(productsRef, where("p_cat", "==", product?.p_cat), limit(7));
  const prodSameCateRes = await getDocs(q);
  const prodSameCate = prodSameCateRes.docs
    .map((pro) => {
      return { ...pro.data(), id: pro.id };
    })
    .filter((pro) => pro.id !== productId);

  return (
    <>
      <div className="product_d_card object-cover md:w-1/2 m-auto">
        <ProductImgCarousel
          imgH={"h-80"}
          imgs={product.p_imgs}
          imgFill={"object-cover"}
        />
        <CarouselDial imgs={product.p_imgs} />
        <div className="p-2">
          <div className="product_d_name ">{product.p_name}</div>
          <div className="wrapper">
            <span className="text-green-700 text-xs">{product.p_cost} SDG</span>
            <span className="category text-xs"> | {product.p_cat}</span>
          </div>
          <div className="product_d_details">
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Sequi,
            similique dolorem, delectus fugit optio provident omnis quia dolorum
            labore magni nostrum quae amet, in beatae ut ab voluptatibus nihil
            quam!
          </div>
          <div className="flex gap-2">
            {/* <WishlistBtn productId={productId} /> */}
            <button className="w-full text-white rounded p-2 bg-green-600">
              Pay Now
            </button>
          </div>
        </div>
      </div>
      <div className="text-2xl ps-2 py-3">Products with same Category</div>

      <ProductsList products={prodSameCate} />
    </>
  );
}
