import { getDoc, doc } from "firebase/firestore";
import { db } from "../../db/firebase";
import ProductImgCarousel from "@/app/comp/carousel";

export const metadata = {
  title: `SPS | product detail`,
  description: "Generated by create next app",
};

export default async function ProductsDetails({ params }) {
  const { productId } = await params;

  const docRef = doc(db, "products", productId);
  const docsnapshot = await getDoc(docRef);
  const product = docsnapshot.exists() ? docsnapshot.data() : {};

  const categories = [
    "MONITORS",
    "SSD",
    "LAPTOP",
    "WEBCAMS",
    "HEADSETS",
    "KEYBOARDS",
    "SPEAKERS",
    "MICROPHONES",
    "TABLETS",
    "PROJECTORS",
    "SCANNERS",
    "HARD_DRIVES",
    "PRINTERS",
    "MOUSES",
    "PC",
    "DESKTOP",
  ];

  function randomImgUrl(seed, w = 400, h = 300) {
    // use picsum with a semi-random seed so URLs differ each run
    const rnd = Math.floor(Math.random() * 10000);
    return `https://picsum.photos/seed/${encodeURIComponent(
      seed + "-" + rnd
    )}/${w}/${h}`;
  }

  const productImageMap = new Map(
    categories.map((cat) => [cat, randomImgUrl(cat)])
  );

  // example usage:
  console.log(productImageMap.get("MONITORS")); // image url for MONITORS

  return (
    <div className="product_d_card">
      <ProductImgCarousel
        imgs={[
          { url: productImageMap.get("MONITORS") },
          { url: productImageMap.get("PC") },
          { url: productImageMap.get("DESKTOP") },
        ]}
      />
      <div className="p-1">
        <div className="product_d_name">{product.p_name}</div>

        <div className="wrapper">
          <span className="cost">{product.p_cost}</span>
          <span className="category"> | {product.p_cat}</span>
        </div>
        <div className="product_d_details">
          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Sequi,
          similique dolorem, delectus fugit optio provident omnis quia dolorum
          labore magni nostrum quae amet, in beatae ut ab voluptatibus nihil
          quam!
        </div>
      </div>
    </div>
  );
}
