export async function generateStaticParams() {
  // console.log(await getProductsIds());
  return await getProductsIds();
}
export const revalidate = 15; // revalidate at most every hour
import { getDoc, doc } from "firebase/firestore";
import { db } from "../../db/firebase";
import ProductImgCarousel from "@/app/comp/carousel";
import { getProductsIds } from "../../actions/product_ids";

export const metadata = {
  title: `SPS | product detail`,
  description: "Generated by create next app",
};

export default async function ProductsDetails({ params }) {
  const { productId } = await params;

  const docRef = doc(db, "productsTest", productId);
  const docsnapshot = await getDoc(docRef);
  const product = docsnapshot.exists() ? docsnapshot.data() : {};

  return (
    <div className="product_d_card">
      <ProductImgCarousel imgs={product.p_imgs} />
      <div className="p-2">
        <div className="product_d_name">{product.p_name}</div>
        <div className="wrapper">
          <span className="text-green-700 text-xs">{product.p_cost} SDG</span>
          <span className="category text-xs"> | {product.p_cat}</span>
        </div>
        <div className="product_d_details">
          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Sequi,
          similique dolorem, delectus fugit optio provident omnis quia dolorum
          labore magni nostrum quae amet, in beatae ut ab voluptatibus nihil
          quam!
        </div>
      </div>
    </div>
  );
}
