import ProductGridCustomData from "../comp/ProductGridOneFile";
import SearchForm from "../comp/SearchForm";
import { getProducts } from "../data/products";
export const metadata = {
  title: "SPS | products Sesrch",
  description: "Generated by create next app",
};

export default async function Home({ searchParams }) {
  const { search_word } = await searchParams;
  let products = [];
  // console.log(search_word);

  if (search_word !== undefined) {
    products = await getProducts("p_name", search_word);
  }

  return (
    <>
      <SearchForm />
      <ProductGridCustomData products={products} />
    </>
  );
}
