import ProductGrid from "@/components/ProductGrid";
import SearchForm from "@/components/SearchForm";
import { getProducts } from "@/services/productsServices";
import { Search } from "lucide-react";
export const metadata = {
  title: "SPS | products Sesrch",
  description: "Generated by create next app",
};

export default async function Home({
  searchParams,
}: {
  searchParams: { search_word?: string };
}) {
  const { search_word } = await searchParams;
  let products = [] as Awaited<ReturnType<typeof getProducts>>;

  if (search_word !== undefined) {
    products = await getProducts("p_name", search_word);
  }

  return (
    <div className="min-h-screen bg-background pb-20">
      <header className="page-header">
        <div className="max-w-7xl mx-auto px-4 sm:px-8">
          <SearchForm />
        </div>
      </header>

      <div className="max-w-7xl mx-auto px-4 sm:px-8">
        {search_word ? (
          <ProductGrid products={products} showSort={true} />
        ) : (
          <div className="flex min-h-[400px] flex-col items-center justify-center rounded-[2rem] bg-card border border-border border-dashed px-4 py-12 text-center">
            <div className="bg-primary/10 mb-6 flex h-16 w-16 items-center justify-center rounded-2xl shadow-sm transition-colors animate-pulse">
              <Search className="h-8 w-8 text-primary" />
            </div>
            <h2 className="max-w-xs text-xl font-black text-foreground">
              Ready to find something?
            </h2>
            <p className="mt-2 max-w-sm text-sm text-muted-foreground font-medium">
              Enter a keyword or product name above to start exploring our
              collection.
            </p>
          </div>
        )}
      </div>
    </div>
  );
}
