// "use client";
import Link from "next/link";
import SearchForm from "../comp/SearchForm";
import { getProducts } from "../data/products";
export const metadata = {
  title: "SPS | products Sesrch",
  description: "Generated by create next app",
};

export default async function Home({ searchParams }) {
  const { search_word } = await searchParams;
  const products = await getProducts(search_word, 6);

  return (
    <>
      <div className="mt-1"></div>
      <SearchForm />
      <div className="list">
        {products && products?.length > 0 ? (
          products.map((row) => (
            <div className="product_card" key={row.id}>
              <Link href={`products/${row.id}`}>
                <div className="img_container">
                  <img src={row.p_img} alt="Product Image" />
                </div>
              </Link>
              <div className="name">{row.p_name}</div>
              <div className="wrapper">
                <span className="cost">{row.p_cost}</span>
                <span className="category"> | {row.p_cat}</span>
              </div>
            </div>
          ))
        ) : (
          <div className="no_product">No products available</div>
        )}
      </div>
    </>
  );
}
