import ProductGrid from "@/components/ProductGrid";
import SearchForm from "@/components/SearchForm";
import { getProducts } from "@/services/productsServices";
import { Search } from "lucide-react";
export const metadata = {
  title: "SPS | products Sesrch",
  description: "Generated by create next app",
};

export default async function Home({
  searchParams,
}: {
  searchParams: { search_word?: string };
}) {
  const { search_word } = await searchParams;
  let products = [] as Awaited<ReturnType<typeof getProducts>>;

  if (search_word !== undefined) {
    products = await getProducts("p_name", search_word);
  }

  return (
    <>
      <SearchForm />
      {search_word ? (
        <ProductGrid products={products} />
      ) : (
        <div className="flex min-h-[400px] flex-col items-center justify-center rounded-xl  px-4 py-12 text-center">
          <div className="bg-white mb-4 flex h-16 w-16 items-center justify-center rounded-full  shadow-sm">
            <Search className="h-8 w-8 text-gray-400" />
          </div>
          <h2 className="max-w-xs text-xl font-semibold text-gray-900">
            Ready to find something?
          </h2>
          <p className="mt-2 max-w-sm text-gray-500">
            Enter a keyword or product name above to start exploring our
            collection.
          </p>
        </div>
      )}
    </>
  );
}
