import { ChartLine, Settings, UserCog2 } from "lucide-react";
import Link from "next/link";

export const metadata = {
  title: "SPS | dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div>
      <Navbar />
      {children}
    </div>
  );
}
function Navbar() {
  return (
    <div className="p-1 flex items-center text-sm border-b">
      <Link className="p-1 flex gap-2 border-r" href="/Dashboard">
        <ChartLine size={20} /> Aanaltics
      </Link>
      <Link className="p-1 flex gap-2 border-r" href="/Dashboard/productsSet">
        <Settings size={20} /> Mange Products
      </Link>

      <Link className="p-1 flex gap-2" href="/Dashboard">
        <UserCog2 size={20} /> Users
      </Link>
    </div>
  );
}
