import { ChartLine, Settings, UserCog2 } from "lucide-react";
import Link from "next/link";

export const metadata = {
  title: "SPS | dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div>
      <Navbar />
      {children}
    </div>
  );
}
function Navbar() {
  return (
    <div className="flex items-center text-sm  border-b flex-wrap">
      <small>
        <Link
          className="p-1 flex items-center gap-1 border-r"
          href="/Dashboard"
        >
          <ChartLine size={16} /> Aanaltics
        </Link>
      </small>
      <small>
        {" "}
        <Link
          className="p-1 flex items-center gap-1 border-r"
          href="/Dashboard/productsSet"
        >
          <Settings size={16} /> Products
        </Link>
      </small>

      <small>
        {" "}
        <Link className="p-1 items-center flex gap-1" href="/Dashboard">
          <UserCog2 size={16} /> Users
        </Link>
      </small>
      <small>
        <Link
          className="p-1 flex items-center gap-1 border-r"
          href="/Dashboard"
        >
          <ChartLine size={16} /> Aanaltics
        </Link>
      </small>
      <small>
        {" "}
        <Link
          className="p-1 flex items-center gap-1 border-r"
          href="/Dashboard/productsSet"
        >
          <Settings size={16} /> Products
        </Link>
      </small>
    </div>
  );
}
