import Link from "next/link";

export const metadata = {
  title: "SPS | dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div>
      <Navbar />
      {children}
    </div>
  );
}
function Navbar() {
  return (
    <div className="dashboard_navbar bg-gray-700 p-1 text-white flex justify-between items-center text-sm">
      <div>
        <Link className="p-1" href="/products">
          Search
        </Link>
        <Link className="p-1" href="/products/productsSet">
          Products Set
        </Link>
        <Link className="p-1" href="/products">
          Orders
        </Link>
      </div>
    </div>
  );
}
